version: "2"
services:
  book:
    build: ./book
    environment:
      - DB_HOST=db
    expose:
      - 5000
    ports:
      - 5000:5000
  db:
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
volumes:
  db:
