version: "3"
services:
  page_sequence:
    image: ghcr.io/hannahellis4242/bpss/book-page-sequence-service:latest
    expose:
      - 3001
    ports:
      - 3001:8080
    restart: always
  web:
    build: .
    expose:
      - 80
    ports:
      - 80:8080
    restart: always