version: "3"
services:
  page_sequence:
    image: ghcr.io/hannahellis4242/bpss/book-page-sequence-service:latest
    restart: always
  sigature_finder:
    image: ghcr.io/hannahellis4242/bsfs/book-signature-finder-service:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: always
  web:
    build: .
    expose:
      - 80
    ports:
      - 80:8080
    restart: always
