version: "2"
services:
  book:
    build: ./server
    expose:
      - 5000
  web:
    build: ./web
    environment:
      - book-host=book
      - book-port=5000
      - client-host=client
      - client-port=3000
    expose:
      - 8080
    ports:
      - 80:8080
  client:
    build: ./client
    expose:
      - 3000
