name: book-finder service CI

on:
  push:
    paths:
      - "book_finder/**"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        working-directory: ./book_finder
        run: npm install
      - name: build
        working-directory: ./book_finder
        run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: test
        working-directory: ./book_finder
        run: |
          npm install
          npm test

  container:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build And Push book Image
        working-directory: ./book_finder
        run: |
          docker build . --tag ghcr.io/hannahellis4242/book-binder/book_finder:latest
          docker push ghcr.io/hannahellis4242/book-binder/book_finder:latest
