name: Docker Image CI - simple_queue

on:
  push:
    paths:
      - "simple_queue/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push simple_queue Image
        run: |
          docker build ./simple_queue --file simple_queue/dockerfile --tag ghcr.io/hannahellis4242/book-binder/simple_queue:latest
          docker push ghcr.io/hannahellis4242/book-binder/simple_queue:latest
