name: Docker Image CI - book_finder

on:
  push:
    paths:
      - "book_finder/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push book_finder Image
        run: |
          docker build ./book_finder --file book_finder/dockerfile --tag ghcr.io/hannahellis4242/book-binder/book_finder:latest
          docker push ghcr.io/hannahellis4242/book-binder/book_finder:latest
