name: Docker Image CI - client

on:
  push:
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push client Image
        run: |
          docker build ./client --file client/dockerfile --tag ghcr.io/hannahellis4242/book-binder/client:latest
          docker push ghcr.io/hannahellis4242/book-binder/client:latest
