name: Docker Image CI - web

on:
  push:
    paths:
      - "web/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push web Image
        run: |
          docker build ./web --file web/dockerfile --tag ghcr.io/hannahellis4242/book-binder/web:latest
          docker push ghcr.io/hannahellis4242/book-binder/web:latest
